# This file is used by your post processor (Staeubli_HSLU_PP_101_neu)
# to generate the appropriate file for your robot.
# You will find your robot program in the same folder where this file is located.
# To avoid showing this file after program generation you can select:
#   Tools->Options->tab Other , then, uncheck "Show programs in Notepad"

import sys
import os
sys.path.append(os.path.abspath(r"""C:/RoboDK/Posts/""")) # temporarily add path to POSTS folder

from Staeubli_HSLU_PP_101_neu import *

def p(x,y,z,r,p,w):
  a = r*math.pi/180.0
  b = p*math.pi/180.0
  c = w*math.pi/180.0
  ca = math.cos(a)
  sa = math.sin(a)
  cb = math.cos(b)
  sb = math.sin(b)
  cc = math.cos(c)
  sc = math.sin(c)
  return Mat([[cb*ca,ca*sc*sb-cc*sa,sc*sa+cc*ca*sb,x],[cb*sa,cc*ca+sc*sb*sa,cc*sb*sa-ca*sc,y],[-sb,cb*sc,cc*cb,z],[0.0,0.0,0.0,1.0]])

print('Total instructions: 13')
r = RobotPost(r"""Staeubli_HSLU_PP_101_neu""",r"""Staubli TX2-40""",6, axes_type=['R','R','R','R','R','R'], ip_com=r"""10.180.30.222""", api_port=20500, prog_ptr=0, robot_ptr=2155823676336)

r.ProgStart(r"""Vakuumgreifer""")
r.RunMessage(r"""Program generated by RoboDK v5.2.1 for Staubli TX2-40 on 26/04/2021 14:08:58""",True)
r.setAcceleration(1.000)
r.RunCode(r"""addConnection('dVacuum','98FE10BA-0446-4B8A-A8CF-35B98F42725A','dio')""")
r.RunCode(r"""setGripperConnection('dVacuum')""")
r.setFrame(p(0,0,0,0,0,0),-1,r"""Staubli TX2-40 Base""")
r.setTool(p(0,0,78,0,0,0),-1,r"""LWS_VakuumGreifer_14""")
r.MoveJ(None,[0,45,45,0,90,0],None)
r.MoveJ(p(254,-30,-190,-180,0,180),[-14.6013,45.4429,110.133,0,24.4243,-14.6013],[0,0,0])
r.MoveJ(p(302.386,-127.49,-273.58,179.566,0,180),[-28.9834,73.1632,77.2956,0,29.5411,-28.5494],[0,0,0])
r.MoveL(p(302.386,-127.49,-323.58,179.566,0,180),[-28.9834,84.9298,68.0635,0,27.0067,-28.5494],[0,0,0])
r.RunCode(r"""setOutput('dVacuum','1')""")
r.MoveL(p(302.386,-127.49,-273.58,179.566,0,180),[-28.9834,73.1632,77.2956,0,29.5411,-28.5494],[0,0,0])
r.MoveJ(p(254,-30,-190,-180,0,180),[-14.6013,45.4429,110.133,0,24.4243,-14.6013],[0,0,0])
r.MoveJ(p(302.386,-127.49,-273.58,179.566,0,180),[-28.9834,73.1632,77.2956,0,29.5411,-28.5494],[0,0,0])
r.MoveL(p(302.386,-127.49,-323.58,179.566,0,180),[-28.9834,84.9298,68.0635,0,27.0067,-28.5494],[0,0,0])
r.RunCode(r"""setOutput('dVacuum','0')""")
r.MoveJ(None,[0,45,45,0,90,0],None)
r.ProgFinish(r"""Vakuumgreifer""")
r.ProgSave(r"""C:/Users/Student/Documents/RoboDK/""",r"""Vakuumgreifer""",False,r"""C:/RoboDK/Other/VSCodium/VSCodium.exe""")
