# This file is used by your post processor (Staeubli_HSLU_PP_101_neu)
# to generate the appropriate file for your robot.
# You will find your robot program in the same folder where this file is located.
# To avoid showing this file after program generation you can select:
#   Tools->Options->tab Other , then, uncheck "Show programs in Notepad"

import sys
import os
sys.path.append(os.path.abspath(r"""C:/RoboDK/Posts/""")) # temporarily add path to POSTS folder

from Staeubli_HSLU_PP_101_neu import *

def p(x,y,z,r,p,w):
  a = r*math.pi/180.0
  b = p*math.pi/180.0
  c = w*math.pi/180.0
  ca = math.cos(a)
  sa = math.sin(a)
  cb = math.cos(b)
  sb = math.sin(b)
  cc = math.cos(c)
  sc = math.sin(c)
  return Mat([[cb*ca,ca*sc*sb-cc*sa,sc*sa+cc*ca*sb,x],[cb*sa,cc*ca+sc*sb*sa,cc*sb*sa-ca*sc,y],[-sb,cb*sc,cc*cb,z],[0.0,0.0,0.0,1.0]])

print('Total instructions: 35')
r = RobotPost(r"""Staeubli_HSLU_PP_101_neu""",r"""Staubli TX2-40""",6, axes_type=['R','R','R','R','R','R'], ip_com=r"""127.0.0.1""", api_port=20500, prog_ptr=0, robot_ptr=2155823676336)

r.ProgStart(r"""Bewegungsattribute""")
r.RunMessage(r"""Program generated by RoboDK v5.2.1 for Staubli TX2-40 on 26/04/2021 13:26:34""",True)
r.setAcceleration(1.000)
r.RunCode(r"""setAccelerationPercentageJoints('30')""")
r.RunCode(r"""setDeccelerationPercentageJoints('30')""")
r.RunCode(r"""setSpeedPercentageJoints('30')""")
r.RunCode(r"""setTranslationalSpeedTool('30')""")
r.RunCode(r"""setRotationalSpeedTool('30')""")
r.setFrame(p(0,0,0,0,0,0),-1,r"""Staubli TX2-40 Base""")
r.setTool(p(0,0,0,0,0,0),-1,r"""""")
r.MoveJ(p(290,35,225,0,90,0),[0,0,90,0,0,-3.50835e-15],[0,0,0])
r.MoveJ(p(380,40,70,-180,0,180),[0.753392,44.2555,52.4194,0,83.3251,0.753392],[0,0,0])
r.MoveJ(p(390,-40,90,180,0,180),[-10.9779,47.3523,41.9944,0,90.6532,-10.9779],[0,0,0])
r.MoveJ(p(420,25,30,-180,0,180),[-1.36528,60.0499,34.3677,0,85.5825,-1.36528],[0,0,0])
r.MoveJ(p(290,35,225,0,90,0),[0,0,90,0,0,-3.50835e-15],[0,0,0])
r.RunCode(r"""setRotationalSpeedTool('1000')""")
r.MoveJ(p(380,40,70,-180,0,180),[0.753392,44.2555,52.4194,0,83.3251,0.753392],[0,0,0])
r.MoveJ(p(390,-40,90,180,0,180),[-10.9779,47.3523,41.9944,0,90.6532,-10.9779],[0,0,0])
r.MoveJ(p(420,25,30,-180,0,180),[-1.36528,60.0499,34.3677,0,85.5825,-1.36528],[0,0,0])
r.MoveJ(p(290,35,225,0,90,0),[0,0,90,0,0,-3.50835e-15],[0,0,0])
r.RunCode(r"""setTranslationalSpeedTool('1000')""")
r.MoveJ(p(380,40,70,-180,0,180),[0.753392,44.2555,52.4194,0,83.3251,0.753392],[0,0,0])
r.MoveJ(p(390,-40,90,180,0,180),[-10.9779,47.3523,41.9944,0,90.6532,-10.9779],[0,0,0])
r.MoveJ(p(420,25,30,-180,0,180),[-1.36528,60.0499,34.3677,0,85.5825,-1.36528],[0,0,0])
r.MoveJ(p(290,35,225,0,90,0),[0,0,90,0,0,-3.50835e-15],[0,0,0])
r.RunCode(r"""setSpeedPercentageJoints('100')""")
r.MoveJ(p(380,40,70,-180,0,180),[0.753392,44.2555,52.4194,0,83.3251,0.753392],[0,0,0])
r.MoveJ(p(390,-40,90,180,0,180),[-10.9779,47.3523,41.9944,0,90.6532,-10.9779],[0,0,0])
r.MoveJ(p(420,25,30,-180,0,180),[-1.36528,60.0499,34.3677,0,85.5825,-1.36528],[0,0,0])
r.MoveJ(p(290,35,225,0,90,0),[0,0,90,0,0,-3.50835e-15],[0,0,0])
r.RunCode(r"""setAccelerationPercentageJoints('100')""")
r.MoveJ(p(380,40,70,-180,0,180),[0.753392,44.2555,52.4194,0,83.3251,0.753392],[0,0,0])
r.MoveJ(p(390,-40,90,180,0,180),[-10.9779,47.3523,41.9944,0,90.6532,-10.9779],[0,0,0])
r.MoveJ(p(420,25,30,-180,0,180),[-1.36528,60.0499,34.3677,0,85.5825,-1.36528],[0,0,0])
r.MoveJ(p(290,35,225,0,90,0),[0,0,90,0,0,-3.50835e-15],[0,0,0])
r.RunCode(r"""setDeccelerationPercentageJoints('100')""")
r.MoveJ(p(380,40,70,-180,0,180),[0.753392,44.2555,52.4194,0,83.3251,0.753392],[0,0,0])
r.MoveJ(p(390,-40,90,180,0,180),[-10.9779,47.3523,41.9944,0,90.6532,-10.9779],[0,0,0])
r.MoveJ(p(420,25,30,-180,0,180),[-1.36528,60.0499,34.3677,0,85.5825,-1.36528],[0,0,0])
r.MoveJ(p(290,35,225,0,90,0),[0,0,90,0,0,-3.50835e-15],[0,0,0])
r.ProgFinish(r"""Bewegungsattribute""")
r.ProgSave(r"""C:/Users/Student/Documents/RoboDK/""",r"""Bewegungsattribute""",False,r"""C:/RoboDK/Other/VSCodium/VSCodium.exe""")
